default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: server_development

test:
  <<: *default
  database: server_test

production:
  <<: *default
  database: <%= ENV["DATABASE_URL"] %>
